const WORD_EMOJI_MAP: Record<string, string> = {
  "сайн байна уу": "👋",
  "сайн уу": "👋",
  "сайн байна": "🙂",
  "баяртай": "👋",
  "баярлалаа": "🙏",
  "уучлаарай": "🙇",
  "тийм": "✅",
  "үгүй": "❌",
  "гуйя": "🙏",
  "дараа уулзъя": "👋",
  "тэр миний найз": "🧑‍🤝‍🧑",
  "би чиний найз": "🧑‍🤝‍🧑",
  "бид найзууд": "👫",
  "найз": "🧑‍🤝‍🧑",
  "мах": "🥩",
  "сүү": "🥛",
  "талх": "🍞",
  "ус": "💧",
  "цай": "🍵",
  "кофе": "☕",
  "будаа": "🍚",
  "өндөг": "🥚",
  "алим": "🍎",
  "гүзээлзгэнэ": "🍓",
  "нэг": "1️⃣",
  "хоёр": "2️⃣",
  "гурав": "3️⃣",
  "дөрөв": "4️⃣",
  "тав": "5️⃣",
  "зүүн": "👈",
  "баруун": "👉",
  "дээш": "👆",
  "доош": "👇",
  "нохой": "🐶",
  "муур": "🐱",
  "морь": "🐎",
  "шувуу": "🐦",
  "улаан": "🟥",
  "цэнхэр": "🟦",
  "ногоон": "🟩",
  "шар": "🟨",
  "цагаан": "⬜",
  "хар": "⬛",
  "улбар шар": "🟧",
  "ягаан": "🌸",
  "нил ягаан": "🟪",
  "хүрэн": "🟫",
  "саарал": "🩶",
  "толгой": "🗣️",
  "нүд": "👁️",
  "ам": "👄",
  "хамар": "👃",
  "чих": "👂",
  "үс": "💇",
  "шүд": "🦷",
  "гар": "✋",
  "хөл": "🦶",
  "хуруу": "👆",
  "зүрх": "❤️",
  "нар": "☀️",
  "бороо": "🌧️",
  "цас": "❄️",
  "салхи": "🌬️",
  "үүл": "☁️",
  "аянга": "⚡",
  "зун": "🌻",
  "өвөл": "⛄",
  "хавар": "🌷",
  "намар": "🍂",

  "hola": "👋",
  "adiós": "👋",
  "gracias": "🙏",
  "por favor": "🙏",
  "lo siento": "🙇",
  "sí": "✅",
  "no": "❌",
  "buenos días": "🌅",
  "buenas noches": "🌙",
  "hasta luego": "👋",
  "de nada": "🙏",
  "estoy bien": "🙂",
  "él es mi amigo": "🧑‍🤝‍🧑",
  "ella es mi amiga": "👭",
  "tú eres mi amigo": "🧑‍🤝‍🧑",
  "amigo": "🧑‍🤝‍🧑",
  "amiga": "👭",
  "manzana": "🍎",
  "naranja": "🍊",
  "plátano": "🍌",
  "fresa": "🍓",
  "uva": "🍇",
  "agua": "💧",
  "leche": "🥛",
  "café": "☕",
  "pan": "🍞",
  "carne": "🥩",
  "arroz": "🍚",
  "huevo": "🥚",
  "izquierda": "👈",
  "derecha": "👉",
  "arriba": "👆",
  "abajo": "👇",
  "perro": "🐶",
  "gato": "🐱",
  "caballo": "🐎",
  "pájaro": "🐦",

  "bonjour": "👋",
  "au revoir": "👋",
  "merci": "🙏",
  "s'il vous plaît": "🙏",
  "pardon": "🙇",
  "oui": "✅",
  "non": "❌",
  "bonsoir": "🌙",
  "à bientôt": "👋",
  "de rien": "🙏",
  "ça va": "🙂",
  "ami": "🧑‍🤝‍🧑",
  "amie": "👭",
  "pomme": "🍎",
  "orange": "🍊",
  "banane": "🍌",
  "fraise": "🍓",
  "raisin": "🍇",
  "eau": "💧",
  "lait": "🥛",
  "vin": "🍷",
  "café au lait": "☕",
  "pain": "🍞",
  "viande": "🥩",
  "riz": "🍚",
  "œuf": "🥚",
  "gauche": "👈",
  "droite": "👉",
  "haut": "👆",
  "bas": "👇",
  "chien": "🐶",
  "chat": "🐱",
  "cheval": "🐎",
  "oiseau": "🐦",

  "hallo": "👋",
  "tschüss": "👋",
  "danke": "🙏",
  "bitte": "🙏",
  "entschuldigung": "🙇",
  "ja": "✅",
  "nein": "❌",
  "guten morgen": "🌅",
  "guten abend": "🌙",
  "bis später": "👋",
  "gern geschehen": "🙏",
  "mir geht es gut": "🙂",
  "freund": "🧑‍🤝‍🧑",
  "freundin": "👭",
  "apfel": "🍎",
  "banane (de)": "🍌",
  "wasser": "💧",
  "milch": "🥛",
  "wein": "🍷",
  "brot": "🍞",
  "fleisch": "🥩",
  "reis": "🍚",
  "ei": "🥚",
  "links": "👈",
  "rechts": "👉",
  "oben": "👆",
  "unten": "👇",
  "hund": "🐶",
  "katze": "🐱",
  "pferd": "🐎",
  "vogel": "🐦",

  "ciao": "👋",
  "arrivederci": "👋",
  "grazie": "🙏",
  "per favore": "🙏",
  "scusa": "🙇",
  "sì (it)": "✅",
  "no (it)": "❌",
  "buongiorno": "🌅",
  "buonanotte": "🌙",
  "a dopo": "👋",
  "prego": "🙏",
  "sto bene": "🙂",
  "amico": "🧑‍🤝‍🧑",
  "amica": "👭",
  "mela": "🍎",
  "arancia": "🍊",
  "fragola": "🍓",
  "uva (it)": "🍇",
  "acqua": "💧",
  "latte": "🥛",
  "vino": "🍷",
  "pane": "🍞",
  "carne (it)": "🥩",
  "riso": "🍚",
  "uovo": "🥚",
  "sinistra": "👈",
  "destra": "👉",
  "su": "👆",
  "giù": "👇",
  "cane": "🐶",
  "gatto": "🐱",
  "cavallo": "🐎",
  "uccello": "🐦",

  "olá": "👋",
  "tchau": "👋",
  "obrigado": "🙏",
  "obrigada": "🙏",
  "desculpa": "🙇",
  "sim": "✅",
  "não": "❌",
  "bom dia": "🌅",
  "boa noite": "🌙",
  "até logo": "👋",
  "estou bem": "🙂",
  "amigo (pt)": "🧑‍🤝‍🧑",
  "amiga (pt)": "👭",
  "maçã": "🍎",
  "laranja": "🍊",
  "morango": "🍓",
  "água": "💧",
  "leite": "🥛",
  "vinho": "🍷",
  "pão": "🍞",
  "arroz (pt)": "🍚",
  "ovo": "🥚",
  "esquerda": "👈",
  "direita": "👉",
  "acima": "👆",
  "abaixo": "👇",
  "cachorro": "🐶",
  "gato (pt)": "🐱",
  "cavalo": "🐎",
  "pássaro": "🐦",

  "こんにちは": "👋",
  "おはよう": "🌅",
  "おはようございます": "🌅",
  "こんばんは": "🌙",
  "さようなら": "👋",
  "ありがとう": "🙏",
  "すみません": "🙇",
  "はい": "✅",
  "いいえ": "❌",
  "またね": "👋",
  "友達": "🧑‍🤝‍🧑",
  "りんご": "🍎",
  "みかん": "🍊",
  "バナナ": "🍌",
  "いちご": "🍓",
  "水": "💧",
  "牛乳": "🥛",
  "ワイン": "🍷",
  "パン": "🍞",
  "肉": "🥩",
  "ご飯": "🍚",
  "卵": "🥚",
  "左": "👈",
  "右": "👉",
  "上": "👆",
  "下": "👇",
  "犬": "🐶",
  "猫": "🐱",
  "馬": "🐎",
  "鳥": "🐦",
};

const FALLBACK_EMOJIS = ["🌟", "💫", "🎈", "🎀", "🌈", "🍀", "✨", "🪄"];

function hashStr(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

export function getWordEmoji(text: string): string {
  const key = text.trim().toLowerCase();
  const direct = WORD_EMOJI_MAP[key];
  if (direct) return direct;
  return FALLBACK_EMOJIS[hashStr(key) % FALLBACK_EMOJIS.length];
}

const CARD_PALETTES = [
  { bg: "from-emerald-100 to-emerald-200", dark: "dark:from-emerald-900/40 dark:to-emerald-800/40", ring: "ring-emerald-300/60" },
  { bg: "from-sky-100 to-sky-200", dark: "dark:from-sky-900/40 dark:to-sky-800/40", ring: "ring-sky-300/60" },
  { bg: "from-amber-100 to-amber-200", dark: "dark:from-amber-900/40 dark:to-amber-800/40", ring: "ring-amber-300/60" },
  { bg: "from-rose-100 to-rose-200", dark: "dark:from-rose-900/40 dark:to-rose-800/40", ring: "ring-rose-300/60" },
  { bg: "from-violet-100 to-violet-200", dark: "dark:from-violet-900/40 dark:to-violet-800/40", ring: "ring-violet-300/60" },
  { bg: "from-orange-100 to-orange-200", dark: "dark:from-orange-900/40 dark:to-orange-800/40", ring: "ring-orange-300/60" },
];

export function getWordPalette(text: string) {
  return CARD_PALETTES[hashStr(text.trim().toLowerCase()) % CARD_PALETTES.length];
}
